server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/b_bank
    username: b_banker
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true